### ISSUE TITLE
Interacting with pill

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#133]
- [ ] add to query / remove from query
- [ ] function control (similar to the left side)

**Comment by vlandham** [comment]
To add some detail here - This is how I interpret this issue:

Pills in Voyager are visually represented as the rounded squares used to indicate the attributes displayed by a particular visual.
 
<img width="311" alt="screen shot 2015-09-24 at 10 53 50 am" src="https://cloud.githubusercontent.com/assets/9369/10081761/5e9d9a60-62ab-11e5-9f9d-98cbe0a3b7c2.png">

They are implemented in `fieldInfo` and listed in `vlplotgroup` inside of `vega-lite-ui`. 

Currently, they perform no actions when clicked. The UI would be more consistent if when clicking a pill above a particular visualization, it would select / deselect the associated attribute in the left attribute panel.

**Comment by kanitw** [comment]
> Currently, they perform no actions when clicked. The UI would be more consistent if when clicking a pill above a particular visualization, it would select / deselect the associated attribute in the left attribute panel.

Actually, I wonder if clicking to deselect would be confusing as well since there is no checkbox here.   
Maybe we have to add some transition to make the state change obvious to users. 

But at the very least, we can imagine that each pill can have popup menu similar to those on the left side -- so people do not have to move their cursor to the left side everytime they want to modify some property.

**Comment by kanitw** [comment]
No longer plan to add this.
