### ISSUE TITLE
Clean up the logo/mark for the project

### ISSUE THREAD

**Issue by iamjessklein** [vega/voyager#188]
I was sketching on the subway, and I whipped up a few versions of a logo. Feel free to use or not use.
I was imagining that on hover it could do a little rotation, kind of like this:

![datavoyager](https://cloud.githubusercontent.com/assets/535012/10101705/3e8f7622-6368-11e5-932f-77de3e691c62.gif)

<img width="472" alt="screen shot 2015-09-25 at 8 37 57 am" src="https://cloud.githubusercontent.com/assets/535012/10101678/2310eef8-6368-11e5-9342-2633c2e8f377.png">

**Comment by vlandham** [comment]
i really love the blue version. we can see what the UW folks feel - but thanks for putting these together!

**Comment by jheer** [comment]
Very cool. I like the blue version, too. Might be fun to also try a version with UW/IDL colors (purple/gold/grey)...

**Comment by domoritz** [comment]
I love them!

**Comment by iamjessklein** [comment]
Thanks
@jheer I'll try to do an iteration of the purple. The purple that I see on the site is #442976 - is that the right one to test out?

This is what the color looks like:

<img width="152" alt="screen shot 2015-09-25 at 3 20 09 pm" src="https://cloud.githubusercontent.com/assets/535012/10110128/304fa2b8-6399-11e5-931c-1bbc080fc896.png">

**Comment by iamjessklein** [comment]
I just tried it in purple (and purple and gold which looked pretty awful). Here's what the purple looks like:

![purple](https://cloud.githubusercontent.com/assets/535012/10110643/8ba594da-639c-11e5-87f2-c1321d8fd5be.png)

**Comment by domoritz** [comment]
Here are the colors for the idl logo

```css
.logo-i { fill: #939597; }
.logo-d { fill: #652c90; }
.logo-l { fill: #d5a928; }
```

and the UW colors https://www.washington.edu/brand/graphic-elements/primary-color-palette/

**Comment by domoritz** [comment]
@iamjessklein I really, really like the logo. Do you want to send a pr with a new logo or should we try to replicate and add it?

**Comment by vlandham** [comment]
We can definitely get the created version. @iamjessklein is also working on a bit of a design update that we want to submit to the vega team for discussion in a day or two. I can coordinate with Jess to get the logo PR going.

**Comment by kanitw** [comment]
Done as of #195
