### ISSUE TITLE
Determine analytics goals

### ISSUE THREAD

**Issue by kadamwhite** [vega/voyager#189]
#149 tracks how we can implement google analytics, but I wanted to open this issue to discuss what types of questions we want to answer. There's two basic types of tracking I can imagine:

- how often specific events occur; *e.g.* how many graphs are interacted with; and
- what flows a user takes through the application

I'd like to get one or two examples of questions we'd ask of either types, to help focus the initial analytics implementation.

**Comment by vlandham** [comment]
One of our basic assumptions about this tool is that it will be more appealing to a wider audience if the process of getting their own data into voyager is easier and more explicit. 

to this end, I would like to track the flows through the add-data popup in terms of how they are used and the frequency of their use. Some questions I could imagine wanting to answer:

* relative use of the different ways to bring in custom data
* difference in time usage for users with sample data vs users with custom data
* difference in fields explored and bookmarking for these two sets

**Comment by domoritz** [comment]
In addition to how people are using our tool(s), we are also interested in which features are actually being used. This will help us to direct development.

**Comment by kadamwhite** [comment]
@domoritz @kanitw @jheer I'd like to ask y'all to weigh in with one or two specific Qs you'd like to have answered—examples could be, "how many graphs do users interact with after loading a different dataset", or "how often do users open the bookmarks menu". My goal in pushing for this specificity is to help us prioritize what flows to track, vs trying to implement everything at once.
