### ISSUE TITLE
Many “visible” but transparent tooltips block “hover” on command buttons

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#200]
Right now we can’t hover/click the command button for the top-left visualization in voyager 

This is recently introduced as we do not have the same problem in the [current online demo](http://vega.github.io/voyager)

This is happening both in master and the `jim/update-ui` branch

![pasted_image_10_15_15__11_38_am](https://cloud.githubusercontent.com/assets/111269/10524535/fd899b3a-7334-11e5-97aa-367d249d96f2.png)

![pasted_image_10_15_15__12_07_pm](https://cloud.githubusercontent.com/assets/111269/10524629/6d16b546-7335-11e5-9c27-5cb906266290.png)

The root cause is probably that now those transparent `._720kb-tooltip` has `visibility: visible;` while they had `visibility: hidden` in the online demo.  

@domoritz @kadamwhite @vlandham  — any idea what’s causing this?

**Comment by vlandham** [comment]
which buttons are they inhibiting? (or an example of one?) i seem to be able to hover over all the vl plot group buttons and they show a hover state. I can also hover over pills and plots...

**Comment by vlandham** [comment]
is this related? https://github.com/720kb/angular-tooltips/issues/95

**Comment by kanitw** [comment]
> which buttons are they inhibiting? (or an example of one?) i seem to be able to hover over all the vl plot group buttons and they show a hover state. I can also hover over pills and plots...

I cannot hover the first (top-left) `vl-plot-group`'s buttons that are covered by tooltips (see screenshot above).

> is this related? https://github.com/720kb/angular-tooltips/issues/95
Looks like it's related.

**Comment by kadamwhite** [comment]
@kanitw what browser are you using, out of curiosity?

**Comment by kanitw** [comment]
> @kanitw what browser are you using, out of curiosity?
Chrome Version 46.0.2490.33 beta (64-bit)

**Comment by kanitw** [comment]
Note that this is a critical issue as I can hardly use.debug voyager at all.  

(Do you guys run into this problem at all?)

**Comment by kadamwhite** [comment]
I've reproduced the issue, I hadn't used debug mode before! (shameful)
