### ISSUE TITLE
Npm run start (aka gulp serve) does not support css style changes in VLUI

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#216]
If we change code, only refresh the browser works. 
However, somehow I need to do `ctrl+d` + `npm run start` for updating stylesheet.

**Comment by kadamwhite** [comment]
`gulp inject` in another terminal while the gulp server is still running should allow command-r to pick up new styles in dependencies like `vlui` Without requiring the command-c

**Comment by kanitw** [comment]
Thanks, that’s a nice workaround although I should really make the watch call inject correctly too.

**Comment by kanitw** [comment]
`gulp inject` is good enough.  We have also fixed this in other offspring projects.
