### ISSUE TITLE
responsive charts?

### ISSUE THREAD

**Issue by mg1075** [vega/voyager#234]
The containers for the charts are responsive when a person re-sizes the browser window, but the charts themselves appear to be frozen. Any plans on having the charts be responsive?

**Comment by kanitw** [comment]
Sounds like a good idea for future feature, but it is not that important for the analysis experience so we do not have plan to support it right now.

**Comment by kanitw** [comment]
More importantly, having varied axis size would make it hard to compare quantity across charts, so while this idea is excellent at the Vega-Lite/Vega level, it might be the best idea for Voyager.  
Thanks for suggesting though!
