### ISSUE TITLE
Rendering bug after I sorted a bar chart

### ISSUE THREAD

**Issue by kristw** [vega/voyager#237]
![image](https://cloud.githubusercontent.com/assets/1659771/12700485/c548d5b0-c799-11e5-9a5c-b50520adb412.png)

**Comment by domoritz** [comment]
Voyager is using an ancient version of Vega-Lite right now. We will update when Vega-Lite 1.0 is releases, which should be very soon.

**Comment by kanitw** [comment]
This is a  bug for 1.0, which we no longer plans to support.
