### ISSUE TITLE
Basic install on README does not result in working version

### ISSUE THREAD

**Issue by willgroves** [vega/voyager#244]
The basic instructions do not seem to produce a working copy of voyager. The online demo version works fine on OSX with Chrome. But **git clone / npm install / npm start** leaves the working copy with missing dependencies. It seems the 'vlui' (vega-lite-ui) module is missing after npm install. But fixing that with `bower install vega-lite-ui` (choosing the 0.13.1 version), still results in more errors. 

```
START:
  Service: Fields
    ✔ should test something
  Service: Visrec
    ✔ should do something
  Directive: encodingVariations
    ✔ should make hidden element visible
  Directive: fieldList
    ✔ should make hidden element visible
  Directive: fieldListItem
    ✖ should make hidden element visible
  Directive: functionList
    ✔ should have correct number of radio
LOG: '[Logging] ', 'FIELDS_CHANGE', '', Object{selected: [], list: []}
LOG: 'gen time – projections ', '', ' :', 0, 'aggregates:', 0, 'encodings:0', 'total:', 0
  Directive: visList
    ✔ should add vis list element

Finished in 0.876 secs / 0.408 secs

SUMMARY:
✔ 6 tests completed
✖ 1 test failed

FAILED TESTS:
  Directive: fieldListItem
    ✖ should make hidden element visible
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not a constructor (evaluating 'Dataset.schema.stats(fieldDef)')
    bower_components/vega-lite-ui/vlui.js:3882:47
    $digest@bower_components/angular/angular.js:17524:25
    src/components/fieldlistitem/fieldlistitem.test.js:35:18
...
```

The gui then allows for selecting a dataset, but the graphs do not appear.

On the brower the first error is:

```
angular.js:13920 TypeError: Cannot read property 'distinct' of undefined
    at Object.cardinality (http://localhost:3006/bower_components/viscompass/compass.js:3691:16)
    at assignQ (http://localhost:3006/bower_components/viscompass/compass.js:605:50)
    at assignField (http://localhost:3006/bower_components/viscompass/compass.js:650:17)
    at Object.genAggregates [as aggregates] (http://localhost:3006/bower_components/viscompass/compass.js:665:5)
    at http://localhost:3006/app/visrec/visrec.service.js:93:35
    at Array.forEach (native)
    at Object.Visrec.update.projections (http://localhost:3006/app/visrec/visrec.service.js:88:19)
    at updateFields (http://localhost:3006/components/vislist/vislist.js:55:25)
    at http://localhost:3006/components/vislist/vislist.js:66:13
    at Scope.$digest (http://localhost:3006/bower_components/angular/angular.js:17524:23)
```

What steps are missing to get to a basic working version? Thanks!

**Comment by darthmall** [comment]
It seems that `vlui.js` is missing from vega-lite-ui in bower_components. After building that separately and copying it over, I got rid of that error, but there are more missing dependencies. Next up was `angular-websql`. After installing that with Bower, I'm running into missing `ui-rangeSlider`.

**Comment by kanitw** [comment]
We're in the process of refactoring [Voyager 2](http://idl.cs.washington.edu/papers/voyager2) into a [React/Redux app](https://github.com/vega/voyager/tree/vy2) which will produce a way more stable codebase, so this problem should disappear. 

We should have a workable version in a month or two.
