### ISSUE TITLE
Method [getNamespace] does not exist

### ISSUE THREAD

**Issue by bassem00** [vega/voyager#246]
when i try to add bread i get this error.

> BadMethodCallException in Controller.php line 82:
> Method [getNamespace] does not exist.

I'm using voyager v 0.9.33

**Comment by kanitw** [comment]
Apologies -- What is bread?

**Comment by kanitw** [comment]
I believe that you're filing a bug for a wrong repository.

**Comment by bassem00** [comment]
When i try to add a BREAD for an existing table , that's the error that i get, I didn't done any changes to the code just installed voyager in a new project.

**Comment by bassem00** [comment]
even after trying this changes #229

**Comment by bassem00** [comment]
> 1. in Controller.php line 82
> 2. at Controller->__call('getNamespace', array()) in VoyagerDatabaseController.php line 164
> 3. at VoyagerDatabaseController->getNamespace() in VoyagerDatabaseController.php line 164
> 4. at VoyagerDatabaseController->prepopulateBreadInfo('data_rows') in VoyagerDatabaseController.php line 152
> 5. at VoyagerDatabaseController->addBread(object(Request))
> 6. at call_user_func_array(array(object(VoyagerDatabaseController), 'addBread'), array(object(Request))) in Controller.php line 55
> 7. at Controller->callAction('addBread', array(object(Request))) in ControllerDispatcher.php line 44
> 8. at ControllerDispatcher->dispatch(object(Route), object(VoyagerDatabaseController), 'addBread') in Route.php line 190
> 9. at Route->runController() in Route.php line 144
> 10. at Route->run(object(Request)) in Router.php line 642
> 11. at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
> 12. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VoyagerAdminMiddleware.php line 32
> 13. at VoyagerAdminMiddleware->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 14. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 15. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
> 16. at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 17. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 18. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
> 19. at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 20. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 21. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> 22. at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 23. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 24. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
> 25. at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 26. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 27. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> 28. at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 29. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 30. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
> 31. at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 32. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 33. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> 34. at Pipeline->then(object(Closure)) in Router.php line 644
> 35. at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 618
> 36. at Router->dispatchToRoute(object(Request)) in Router.php line 596
> 37. at Router->dispatch(object(Request)) in Kernel.php line 268
> 38. at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
> 39. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> 40. at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
> 41. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> 42. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> 43. at Pipeline->then(object(Closure)) in Kernel.php line 150
> 44. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
> 45. at Kernel->handle(object(Request)) in index.php line 54
> 46. at require_once('C:\Users\bhp\test\public\index.php') in server.php line 21

**Comment by curran** [comment]
@bassem00 It looks like you've got the wrong GitHub repository (check out the [README](https://github.com/vega/voyager)). I believe you're looking for this one https://github.com/the-control-group/voyager

**Comment by domoritz** [comment]
I think a problem might be that the name and logos are very similar ;-)

Here is our logo
![logo](https://cloud.githubusercontent.com/assets/589034/20769950/dd9795e4-b6f8-11e6-9612-7426c040e541.png)


Here is the the-control-group/voyager logo
![large-logo-icon](https://cloud.githubusercontent.com/assets/589034/20769926/bcbf8106-b6f8-11e6-98a4-f90b370d1b03.png)

@bassem00 how did you find this repo? What search term were you using? @curran is there a way to disambiguate?

**Comment by bassem00** [comment]
yes, i made a mistake , Sorry.

**Comment by curran** [comment]
@domoritz I think it's already pretty differentiated.
