### ISSUE TITLE
error when trying to create new table in database

### ISSUE THREAD

**Issue by bassem00** [vega/voyager#247]
i get this error when trying to create new table in database.

![untitled-1](https://cloud.githubusercontent.com/assets/23621653/20731542/19be8668-b68b-11e6-83b9-9a7e316902ea.png)

I'm using voyager v 0.9.33

**Comment by kanitw** [comment]
This seems to be a specific error in php, which is not used in our project.  I'm not sure why you're filing a bug here.   Plus, we don't have version 0.9.33.  

I believe that you're filing a bug for a wrong repository.
