### ISSUE TITLE
deploying problem

### ISSUE THREAD

**Issue by Gyingguo** [vega/voyager#248]
hi all. 

When I deployed voyager, I met a problem. After I ran "npm install", I ran "npm start". It failed. The first question is "Module 'vlui' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.". I fixed it by the solution from https://docs.angularjs.org/error/$injector/nomod. But after this question, I met another one as it's below. I can open the page of http://localhost:3000/, but there is nothing. Could you tell me more about the deloying?

 npm start

> voyager@0.9.0 start D:\workspace\voyager
> gulp serve

[13:27:56] Using gulpfile D:\workspace\voyager\gulpfile.js
[13:27:56] Starting 'styles'...
[13:27:56] Starting 'jshint'...
[13:27:56] gulp-inject 6 files into index.scss.
[13:27:56] Finished 'styles' after 687 ms
[13:27:56] Starting 'inject'...
[13:27:56] gulp-inject 1 files into index.html.
[13:27:56] gulp-inject 10 files into index.html.
[13:27:57] Finished 'jshint' after 770 ms
[13:27:57] Finished 'inject' after 290 ms
[13:27:57] Starting 'watch'...
[13:27:57] Finished 'watch' after 32 ms
[13:27:57] Starting 'serve'...
[13:27:57] Starting 'partials'...
[13:27:57] Finished 'serve' after 83 ms
[13:27:57] Finished 'partials' after 104 ms
[13:27:57] Starting 'test:auto'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please                                                                                                         use
  server = new Server(config, [done])
  server.start()
instead.
07 12 2016 13:27:57.281:WARN [watcher]: Pattern "D:/workspace/voyager/src/vendor                                                                                                        /*.js" does not match any file.
07 12 2016 13:27:57.343:WARN [karma]: No captured browser, open http://localhost                                                                                                        :9875/
07 12 2016 13:27:57.359:INFO [karma]: Karma v1.3.0 server started at http://loca                                                                                                        lhost:9875/
07 12 2016 13:27:57.359:INFO [launcher]: Launching browser PhantomJS with unlimi                                                                                                        ted concurrency
07 12 2016 13:27:57.390:INFO [launcher]: Starting browser PhantomJS
07 12 2016 13:27:58.993:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on s                                                                                                        ocket /#tB6ucU8RhYeejUT8AAAA with id 89999520

START:
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000/
    External: http://137.189.90.42:3000/
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://137.189.90.42:3001
 ---------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src
[BS] Watching files...
  Service: Fields
    × "before each" hook: WorkFn for "should test something"
  Service: Visrec
    × "before each" hook: WorkFn for "should do something"
  Directive: encodingVariations
    × should make hidden element visible
  Directive: fieldList
    × should make hidden element visible
  Directive: fieldListItem
    × should make hidden element visible
  Directive: functionList
    √ should have correct number of radio
  Directive: visList
    × should add vis list element

Finished in 0 secs / 0.016 secs

SUMMARY:
√ 1 test completed
× 6 tests failed

FAILED TESTS:
  Service: Fields
    × "before each" hook: WorkFn for "should test something"
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    [$injector:unpr] Unknown provider: FieldsProvider <- Fields
    http://errors.angularjs.org/1.5.9/$injector/unpr?p0=FieldsProvider%20%3C-%20                                                                                                        Fields
    bower_components/angular/angular.js:4554:86
    getService@bower_components/angular/angular.js:4707:39
    bower_components/angular/angular.js:4559:48
    getService@bower_components/angular/angular.js:4707:39
    injectionArgs@bower_components/angular/angular.js:4732:68
    invoke@bower_components/angular/angular.js:4754:31
    WorkFn@bower_components/angular-mocks/angular-mocks.js:3098:26
    inject@bower_components/angular-mocks/angular-mocks.js:3065:28
    src/app/fields/fields.test.js:15:20
    global code@src/app/fields/fields.test.js:5:9

  Service: Visrec
    × "before each" hook: WorkFn for "should do something"
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    [$injector:unpr] Unknown provider: VisrecProvider <- Visrec
    http://errors.angularjs.org/1.5.9/$injector/unpr?p0=VisrecProvider%20%3C-%20                                                                                                        Visrec
    bower_components/angular/angular.js:4554:86
    getService@bower_components/angular/angular.js:4707:39
    bower_components/angular/angular.js:4559:48
    getService@bower_components/angular/angular.js:4707:39
    injectionArgs@bower_components/angular/angular.js:4732:68
    invoke@bower_components/angular/angular.js:4754:31
    WorkFn@bower_components/angular-mocks/angular-mocks.js:3098:26
    inject@bower_components/angular-mocks/angular-mocks.js:3065:28
    src/app/visrec/visrec.service.test.js:17:20
    global code@src/app/visrec/visrec.service.test.js:6:9

  Directive: encodingVariations
    × should make hidden element visible
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    expected 0 to deeply equal 1

  Directive: fieldList
    × should make hidden element visible
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    expected 0 to deeply equal 2

  Directive: fieldListItem
    × should make hidden element visible
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    expected 0 to deeply equal 1

  Directive: visList
    × should add vis list element
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    expected 0 to deeply equal 1

**Comment by kamilchm** [comment]
I don't see anything after `npm start` too.
All I get is js error shown in browser console:
```
Failed to instantiate module vlui due to:
```

**Comment by kanitw** [comment]
We're in the process of refactoring [Voyager 2](http://idl.cs.washington.edu/papers/voyager2) into a [React/Redux app](https://github.com/vega/voyager/tree/vy2) which will produce a way more stable codebase, so this problem should disappear. 

We should have a workable version in a month or two, so you might want to re-check again later.
