### ISSUE TITLE
Setup Webpack-Dev-Server with HMR

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#250]
Currently webpack-dev-server somehow does not update the build properly.

(For now, I'm using `npm run watch` and use `python -m SimpleHTTPServer <port>` to serve the app.)

## TODO

- [ ] Make webpack-dev-server at least compile properly.  This should allow us to modify a file and refresh the browser to get latest build.) 
- [ ] Support Hot Module Replacement (Update Content without refresh)
  - [ ] CSS
  - [ ] React Components

## Potentially Useful Resources

 http://gaearon.github.io/react-hot-loader/
https://medium.com/@rajaraodv/webpacks-hmr-react-hot-loader-the-missing-manual-232336dc0d96#.aytuhxvht
https://webpack.js.org/guides/hmr-react/
(Not sure if it is already supported by Redux though.)

**Comment by kanitw** [comment]
cc: @felixcodes -- if you're looking for a challenging and extremely helpful issue, this is one!

(This will obviously speed up our development a lot in long run.)

**Comment by saulshanabrook** [comment]
>Currently webpack-dev-server somehow does not update the build properly.

I just tried starting the dev server with `npm run start` and it seems to be updating when I change a file:

![](https://fat.gfycat.com/ImmediateHeftyGrayfox.gif)

Could you clarify what was broken? I am happy to start working on HMR if this part is done already.

**Comment by tafsiri** [comment]
This is also working on my end using both yarn start and npm start. If @kanitw you have a moment to confirm we can probably close this.

**Comment by kanitw** [comment]
Yeah it's working.  I'll keep this open and rename the issue as it's still nice to have HMR.
