### ISSUE TITLE
[Feature request] change data from an api call

### ISSUE THREAD

**Issue by QuantumInformation** [vega/voyager#263]
ATM I need to point to a json file to add data from a URL. Would be great to also support getting data from an api call, 
eg http://api.openweathermap.org/data/2.5/forecast?q=London,uk&mode=json&appid=fbdccfd084f3904f4953985dd358c569

**Comment by kanitw** [comment]
If your API return JSON file in the right format, it should just work.  The problem is probably that the format is not correct (as described in #264).

**Comment by QuantumInformation** [comment]
I see, it would be nice to be able to format the data as it comes back, perhaps your UI could offer such a feature in future.

![image](https://cloud.githubusercontent.com/assets/216566/23034999/a7214360-f475-11e6-97db-54417b5c6f22.png)
