### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by jdittrich** [vega/voyager#286]
Story: As an interested developer I may want to contribute to voyager. My first step would be getting it running.

Problem: There are no build instructions. I tried with `npm install` which failed me with an error on `No compatible version found: extract-text-webpack-plugin@beta`

Possible solution: Add instructions of how to run voyager from this repo.

**Comment by domoritz** [comment]
We suggest yarn to make sure that you have exactly the same versions that we use. Detailed instructions for how to set up voyager are forthcoming.

**Comment by kanitw** [comment]
Thanks for feedback! -- I just added more instruction.  Feel free to create more issues if you have any other feedback! :)
