### ISSUE TITLE
Voyager Components

### ISSUE THREAD

**Issue by rgbkrk** [vega/voyager#292]
Really excited to see this! I came back over to check out voyager and polestar to try giving some default visualization of our table outputs in https://github.com/nteract/nteract/pull/1534 for nteract (and Jupyter). Do you think you'll be exporting any of the components out of here?

/cc @gnestor and @peggyrayzis who are likely to be interested in this. 😄

**Comment by kanitw** [comment]
Hi, 

As you might have noticed, we are re-building Voyager 2 (with React+Redux) in this repo, so it should be quite easy to export component from our project (as compared to the previous angular prototype).

**Comment by kanitw** [comment]
Closing as we have broken this into multiple issues and also already have some basic support for this.

**Comment by rgbkrk** [comment]
Thank you!
