### ISSUE TITLE
Deployment? 

### ISSUE THREAD

**Issue by domoritz** [vega/voyager#303]
I'm wondering whether you will deploy the new version at http://vega.github.io/voyager or some other URL? I think it would be good to keep Voyager 1 behind the current URL.

**Comment by kanitw** [comment]
Not sure why you want the url to point to the old Voyager 1.  

I'm gonna move the old Voyager 1 and 2 to http://vega.github.io/voyager1-archive (and  http://vega.github.io/voyager1-archive) once this version is ready.

**Comment by domoritz** [comment]
What papers or other documents link to voyager where people might expect
voyager 1?

**Comment by kanitw** [comment]
> What papers or other documents link to voyager where people might expect voyager 1?

They will then see a newer version of Voyager that is more powerful and stable. 
Plus, I don't really know if such reference exists.

**Comment by domoritz** [comment]
If no refs exist, I don't care too much about consistent urls. Otherwise I
do.
