### ISSUE TITLE
Problem loading Excel/CSV into datavoyager

### ISSUE THREAD

**Issue by Bondifrench** [vega/voyager#311]
First, awesome project and congratulations on the release of `Voyager 2.0`.
Complete newbie in using `Vega/Voyager` here, I was trying to load a dataset `Add Dataset > Paste or Upload Data > Choose File` that is in an Excel spreadsheet. I thought transforming into a CSV file would help but I keep getting an error:
`Invalid file type: File must be one of following types: [text/csv, text/json, text/tsv]`

Any advice on what I should do to resolve this?

Cheers

**Comment by domoritz** [comment]
Thank you! If your data is not secret, try uploading it to https://gist.github.com/ and use the url from there. If you can send us the link to your gist, we can look into it.

**Comment by Bondifrench** [comment]
Nice to see another Dominik!
I have put the data [here](https://gist.github.com/Bondifrench/e6be03fcaa8f643756c8ab3eafbff395), with no labels, so no risk of privacy problems.
Wonder if the problem is with the file type or the data itself.

**Comment by domoritz** [comment]
Unfortunately, there is no standard for CSV but we require a header. Can you add one and then try again?

**Comment by Bondifrench** [comment]
I added a header, see [here](https://gist.github.com/Bondifrench/978f78f24c638546356af7610487c786), still doesn't work

**Comment by domoritz** [comment]
Works for me (use url https://gist.githubusercontent.com/Bondifrench/978f78f24c638546356af7610487c786/raw/28f0ef243f668630dfe676658b6d611d9170425c/InDDHeader.csv)

<img width="1675" alt="screen shot 2017-04-30 at 23 39 36" src="https://cloud.githubusercontent.com/assets/589034/25573914/556a9194-2dfe-11e7-8277-89d695f97bdd.png">

**Comment by Bondifrench** [comment]
Ah! thank you! Is there a way to have the date column categorized as `Temporal Filed` and not a 'Categorical Field'?

**Comment by domoritz** [comment]
@Bondifrench Yes, you need to format it using a standard format that javascript understands. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse. 

Unfortunately Voyager's data import is not very forgiving at the moment as we are focusing on other areas. We hope that we can benefit from other tools out there but haven't found a god way to integrate yet.
