### ISSUE TITLE
Add APIs to load dataset from outside 

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#313]
## Current Behavior

To give some context of what the app is currently doing: 

1) When the application start, we load the [`DEFAULT_DATASET`](https://github.com/vega/voyager/blob/vy2/src/models/dataset.ts#L16).  

2) We allow users to change the dataset using the [DatasetSelector](https://github.com/vega/voyager/blob/vy2/src/components/data-pane/dataset-selector.tsx), which in turn calls [`datasetUrlLoad`](https://github.com/vega/voyager/blob/vy2/src/actions/dataset.ts#L28), which is a `ThunkAction`.

This `datasetUrlLoad` calls CompassQL's buildSchema and dispatches the `DATASET_URL_RECEIVE` to update the `dataset` in the model. 

Note: 
- Note that the default dataset and the Dataset Selector UI are not ideal behavior -- they are just placeholder for initial development. 
- I only set up React's asynchronous using redux-thunk because it's included in the main redux tutorial, but if you have a good reason why we should choose other asynchronous action pattern, we can easily swap to other as we're still in an early stage. 

## What to do

- [x] Design an API (probably in [`app.tsx`](https://github.com/vega/voyager/blob/vy2/src/components/app.tsx)) to have a command to load dataset from outside -- either as a URL, or loading the data directly. 

- [ ] We probably have to refactor the `dataset` in the model somehow to make it more flexible and better support server-side (https://github.com/vega/voyager/issues/314).

- [ ] (Advance) How should our application be synchronized with external data if it can be changed -- e.g., with Jupyter Lab)

**Comment by tafsiri** [comment]
@kanitw and @vlandham i've made a few issues that relate to this but are more granular (listed above). Feel free to take a look and comment. I think it would be nice to close this issue out in favor of more granular ones. The second bullet above seems covered by #314. The third one might also have solution, but we'd probably have to evaluate that in the light of an embedding.
