### ISSUE TITLE
Add Server Mode

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#314]
Currently, all query processing happens in the client.

- When a new dataset is loaded, we call the [`buildSchema` method](https://github.com/vega/voyager/blob/vy2/src/actions/dataset.ts#L42) to create a schema from a dataset and calculate basic statistics. 

- When the shelf updates, we call CompassQL's [`recommend` method directly in the selector](https://github.com/vega/voyager/blob/vy2/src/selectors/index.ts#L24).  (Once I implement related views, we will also make multiple calls to the CompassQL to generate other recommendations as well.) 

It would be great to add a server (probably express.js) to allow this computation to happen separately on a server. 

Note that we should still support running in a client-only mode.

**Comment by domoritz** [comment]
Can you elaborate what this is?
