### ISSUE TITLE
Support multiple external data sources

### ISSUE THREAD

**Issue by tafsiri** [vega/voyager#324]
Spinning off from #313 

Should voyager support programmatic setting of multiple data sources that would populate the data source selector?

**Comment by kanitw** [comment]
This is a very good question.  

To simplify our scope, maybe we can just display the dataset name without the select box when Voyager is wrapped?  (The select box is a just a placeholder UI after all.)

One related question would be how would we implement UI for importing data from file say from App like Electron.  (Should the API provide some action that external app can listen to and we provide a button that triggers such action?)

In any case, we should consider joining multiple datasets out of scope for our project.

**Comment by tafsiri** [comment]
Ah okay, i wasn't thinking so much of supporting joining multiple datasets, but an implemented being able to populate a dataset selector. 

I've been thinking of the following spec/description for data to passed into voyager and its ends up being fairly uniform

#### Use case 1. Load from a url

```
data = [
 {  "type": "url", name: "Foo", url: "http://example.com/data.json"}
]
```

#### Use case 2. Already loaded data
```
data = [
  { "type": "dataset", name: "Foo", "data": [] }
]
```

#### Use case 3. Populate 'dataset selector' with multiple options, note that we can probably support mixing types.
```
data = [
  { "type": "dataset", name: "Foo", "data": [] },
  {  "type": "url", name: "Foo", url: "http://example.com/data.json"}
]
```

All of these use cases could boil down to populating a list of available datasets, and setting the current dataset to the first thing in the list. And then letting the dataset selector take over from there. I think that could potentially be useful to an embedder.

This could allow something like electron to enumerate a set of urls that the app can load (via file url) that could be displayed inside the app. But could also allow an embedder/electron app to create their own data upload UI (if the data load is not specifiable via url). I think separately from this we would allow some configuration to determine whether the "Change dataset" option is visible (currently represented by the select box). 

But I agree on splitting out the name of what is currently selected from what the options are.

**Comment by kanitw** [comment]
I agree that an API to populate a list of available datasets may be useful, don't think it is necessary especially for an MVP / initial PR.  

I suspect that people would open one dataset at a time anyway so we can just provide an API to load a dataset.  A loaded dataset is then added to the list of datasets.   We can add this special API later if we still want to. 

Notes:
1)  I imagine the dataset UI will be more like https://vega.github.io/voyager2/ (not a select box like we have).  We could add the loaded dataset to the list. 

![pasted_image_5_17_17__2_15_pm](https://cloud.githubusercontent.com/assets/111269/26176540/58e72afc-3b0b-11e7-82a1-d9f71bc8176b.png)

(Maybe we will remove the "exploring sample dataset" label .. not sure) 

2) (Very minor point) Let's avoid overloading the term data.  Maybe let's use the following terms:

```
datasets = [
  { "type": "dataset", name: "Foo", "values": [] }  // values in the dataset (consisistent with Vega/Vega-Lite)
]
```

**Comment by kanitw** [comment]
Actually looking https://github.com/vega/voyager/pull/322/files, it seems like when the external app changes dataset, it will re-render the whole Voyager app, which is fine. 

So I think my earlier comment would fit well in this scenario?

> To simplify our scope, maybe we can just display the dataset name without the select box when Voyager is wrapped?

**Comment by kanitw** [comment]
(I start liking this idea less) 

> I suspect that people would open one dataset at a time anyway so we can just provide an API to load a dataset. A loaded dataset is then added to the list of datasets. We can add this special API later if we still want to.

**Comment by tafsiri** [comment]
Ignore my dataformat suggestions in here. Kanit pointed me to the vega-lite/data interface and i think we can use that directly and try and co-evolve it as needed or extend it at some point if that is needed.

**Comment by kanitw** [comment]
I think I'll close this for now as i think it is not important.
