### ISSUE TITLE
Research ways to trigger result action creators from redux data store

### ISSUE THREAD

**Issue by vlandham** [vega/voyager#329]
Issue: We want to update recommendations and other (potentially) server-side calculations any time the shelf or input data change. With #328  we do this at the component level - triggering the `resultRequest` action creator when the shelf component or data selector component has updated props. 

A more elegant solution, perhaps, would be to trigger this action creator directly in the data store, or as a side effect of the shelf / data data stores changing. As reducers are meant to be pure functions, this could go against Redux best practices. 

There are tools/existing solutions that might potentially help if we want to move this to a different part of the app:

* [Redux Loop](https://github.com/redux-loop/redux-loop)
* [Redux Saga](https://github.com/redux-saga/redux-saga)
* [Actors article](http://jamesknelson.com/join-the-dark-side-of-the-flux-responding-to-actions-with-actors/)
* [Redux Side Effect Discussion](https://github.com/reactjs/redux/issues/1528)

Would want to evaluate solutions wrt ability to test as well.

**Comment by kanitw** [comment]
At very least, we should consider an appropriate component to trigger this change.  
Right now, this is triggered in `DatasetSelector` and `EncodingPanel`, which seem a bit arbitrary.  
(Why not `DataPanel` rather than `DatasetSelector`?)

**Comment by kanitw** [comment]
Currently I simply use a store listener in https://github.com/vega/voyager/pull/462
but haven't written test.  We need to consider if it is too complicated to write a test for this approach, and re-consider.

**Comment by vlandham** [comment]
store listener approach seems like the way to go. Thanks for figuring this out.
