### ISSUE TITLE
create express app server

### ISSUE THREAD

**Issue by vlandham** [vega/voyager#330]
Part of #314 Should import compassql and be able to respond to `recommend` and `getSchema` 

can be developed in voyager project for now. we could move it out to its own repo if need be. 

One open question will be how flexible the serialization of the inputs to `recommend` will need to be.

**Comment by kanitw** [comment]
Thanks for creating this issue.  

I was thinking a bit more -- maybe it's just nice to start this as a separate repository? The benefit is that we will have a separate package.json and its own dependencies for the voyager-server.   I can help create a repo if you agree.  

> One open question will be how flexible the serialization of the inputs to recommend will need to be.

The `query` itself is already a vanilla JS object, so should be already serializable.  
The question is how do we deal with `schema`.  A few options

1) Just build schema in the server as well and the schema for the dataset will be stored on the server. Thus, we don't have to send the schema around every time.  
However, this means that if we modify the schema (e.g., by changing a field's type), we will have to send schema change request the server.

2) Alternatively, we can refactor the Schema object in CompassQL to be more serializable but it seems a bit like an overkill to pass this around everytime.  (Thus I'm leaning toward 1.)

**Comment by vlandham** [comment]
But with option # 1 - your server would have to be stateful - correct? And thus it would be difficult for it to support multiple instances of a client connecting to it to get recommendations, right?

The other piece that needs to be serializable is the output - the recommend results - back to the client. Looking at this briefly, there could be some difficulty in serializing the `_items` of the `SpecQueryModelGroup ` as it can be an array of `SpecQueryModel` or `SpecQueryModelGroup`. 

I guess my first thought for making all this work is to have serialize / deserialize methods for the types in question - that can reduce the class instance to just a json object, and then use that json object to instantiate a class. 

these methods would make most sense inside the compassql library - to me. But i might be missing something in terms of other approaches to implement. 

I don't think i would suggest going down the stateful route at this point.

**Comment by vlandham** [comment]
I just found this tool: [class-transformer](https://github.com/pleerock/class-transformer) - not sure its the solution we want, but in a similar vein as what i was thinking.

**Comment by vlandham** [comment]
For input, what if we passed the raw data to the server and it did the transformation to schema? Then we would know we wouldn't have issues We could optionally look at caching on the server side - if the data hasn't changed, pull out the cached schema

**Comment by kanitw** [comment]
> But with option # 1 - your server would have to be stateful - correct? And thus it would be difficult for it to support multiple instances of a client connecting to it to get recommendations, right?

 I don't think having multiple instances of a client connecting to a server is particularly important.  
However, I agree that having stateful server is not ideal -- at least for the initial prototype. 

> The other piece that needs to be serializable is the output - the recommend results - back to the client. Looking at this briefly, there could be some difficulty in serializing the _items of the SpecQueryModelGroup as it can be an array of SpecQueryModel or SpecQueryModelGroup.

I think this should not be too hard to refactor.  Both `SpecQueryModel` and `SpecQueryModelGroup` mainly provide helper methods.   

The [class-transformer](https://github.com/pleerock/class-transformer) looks interesting as one option.  Another option would be just refactoring `SpecQueryModel` and `SpecQueryModelGroup` directly.  (I am really happy with the way they serve as CompassQL's recommendation outputs anyway.)

**Comment by kanitw** [comment]
> For input, what if we passed the raw data to the server and it did the transformation to schema? Then we would know we wouldn't have issues We could optionally look at caching on the server side - if the data hasn't changed, pull out the cached schema

Note that it probably doesn't work since raw data does not have information about `type` of measurements (quantitative / nominal / ordinal).  We can infer the default `type` of measurement from the schema, but they are not always correct.  Thus, users should be able to override these in the UI. 

One way that we could make this work without stateful APIs is to allow passing type "override" information to the server.  (If this override is not passed, then we use the default inferred type.) 

cc: @AkshatSh -- This is relevant to you.

**Comment by vlandham** [comment]
thanks for the feedback @kanitw  - yes seeing more of how the schema is built, I see what you mean. Ensuring that the schema is serializable probably won't be a huge issue so we can plan on not using additional libraries, and just working to refactor this and the  SpecQueryModel(Group) to be more serializable.

**Comment by kanitw** [comment]
I was a skimming the code.  There are some relevant parts:

1) `SpecQueryModelGroup` in CompassQL should be serialized easily. 
The only helper method needs for the client side is `getTopSpecQueryModel` 

We could add a new interface `SpecQueryGroup<T>` that have similar properties but have `items: (SpecQueryGroup<T> | T)[]`. We can then rewrite `getTopSpecQueryModel` that works with the pure object version.  (We can no longer use`instanceof` check, so we will have to introduce a type guard function for `SpecQueryGroup` instead.)

2) SpecQueryModel is a bit trickier to refactor.  

However, we don't really use all information in the Voyager client.  We have `PlotObject` interface and `plotObject` method in `plot.ts`. So at a first step to implement server we could run these methods on the server as well and make `SpecQueryGroup<PlotObject>` our serializable object.

Notes:
1) `PlotObject` is a specific subset of things that we use in Voyager so it should stay in Voyager codebase.  However, I think we should still later refactor output of CompassQL's `recommend` method -- but we can punt on that to focus more on the server first.  

2) `PlotObject` is obviously not an ideal name, feel free to suggest a better name.

**Comment by vlandham** [comment]
Sounds good. I've started down this path, and will put a PR in compassql for the new `SpecQueryGroup<T>`

Though, so far, I've found success implementing it as a class to extend rather then just an interface:

```js
export class SpecQueryGroup<T> {

  private _name: string;
  private _path: string;
  private _items: (SpecQueryGroup<T> | T)[]; 
  private _groupBy: GroupBy; 
  private _orderGroupBy: string | string[];

  constructor(name: string = '', path: string = '', items: (T | SpecQueryGroup<T>)[] = [],
              groupBy: GroupBy = undefined, orderGroupBy: string | string[] = undefined) {
    this._name = name;
    this._path = path;
    this._items = items;
    this._groupBy = groupBy;
    this._orderGroupBy = orderGroupBy;
  }

  public isItemSpecQueryGroup(item: SpecQueryGroup<T> | T): item is SpecQueryGroup<T> {
    return (<SpecQueryGroup<T>>item).getTopSpecQueryItem !== undefined;
  }
  public getTopSpecQueryItem(): T {
    const topItem = this._items[0];
    if (this.isItemSpecQueryGroup(topItem)) {
      return topItem.getTopSpecQueryItem();
    } else {
      return topItem;
    }
  }

 // ... accessors
}

export class SpecQueryModelGroup extends SpecQueryGroup<SpecQueryModel> {

  public getTopSpecQueryModel(): SpecQueryModel {
    return this.getTopSpecQueryItem();
  }
}
```

Does this make sense to you?

i've started adding tests in compassql for `SpecQueryModelGroup` as well.

**Comment by kanitw** [comment]
For the code above, it seems like we can just have a single `SpecQueryModelGroup` class that's a generic class?

**Comment by vlandham** [comment]
but isn't the point that these Groups won't always be storing `Model`s ? 

so, in Voyager, we can make a:

```
class SpecQueryPlotObjectGroup extends SpecQueryGroup<PlotObject> {
...
}
```

easily?

**Comment by kanitw** [comment]
I mean this part class with `getTopSpecQueryModel()` seems a bit unnecessary:

```

export class SpecQueryModelGroup extends SpecQueryGroup<SpecQueryModel> {

  public getTopSpecQueryModel(): SpecQueryModel {
    return this.getTopSpecQueryItem();
  }
}
```

Maybe we can declare

```
type SpecQueryModelGroup = SpecQueryGroup<SpecQueryModel>;
```

and use `getTopSpecQueryItem()` instead of a special `getTopSpecQueryModel` ?

**Comment by vlandham** [comment]
sounds good! I'll try it out.

**Comment by kanitw** [comment]
@vlandham  -- should we close this?

**Comment by vlandham** [comment]
sounds good. for other changes we can use the appropriate repo.
