### ISSUE TITLE
Mechanism to sync with external data when it's changed

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#332]
Forked from #313

In #313, @tafsiri mentions that one solution would be:

>  we'd probably have to evaluate that in the light of an embedding.

**Comment by tafsiri** [comment]
I think once #324 lands we can evaluate this further, however at the moment the `updateData()` function would be how one updates the data. However do you see other requirements/scenarios we would want to be able to handle?

**Comment by kanitw** [comment]
seems like `updateData()` should be sufficient so let's close this for now. 
We can see if there are other requests in the future.
