### ISSUE TITLE
Refactor schema to conform with JSON Table Schema

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#338]
Panda and Jupyter Lab are all using this format.

See https://specs.frictionlessdata.io/table-schema/ for more info.

**Comment by ellisonbg** [comment]
Nice! I think this would go a long way in allowing different libraries to share tabular data.

**Comment by ellisonbg** [comment]
Don't know if it of interest, but we are working on a TypeScript interface/types for the JSON table schema. Fairly simple stuff, but can post a link to it once it is on Github.

**Comment by domoritz** [comment]
CC @rufuspollock

**Comment by vlandham** [comment]
Current plan: I believe we can satisfy the basic requirements of Table Schema fairly easily with the following changes to Compassql' `FieldSchema` interface:

* rename `field` to `name` - the required ID of the field
* rename `type` to `vlType` - as this is additional data not captured in table schema
* rename `primitiveType` to `type` 
* rename primitiveType `date` to `datetime`.

These changes, i believe, will be enough to make `Schema` and `FieldSchema` conform to the table schema spec. We will probably also want a method to augment an input table schema into a `Schema` instance (augmenting it with the stats and other fields). 

we might also want a method to output a barebones table schema output from a compassql's `Schema` (removing these additional fields).

Thoughts @kanitw ?

**Comment by vlandham** [comment]
we can also better represent this extension using a separate interface. Something like:

```
export interface TableSchemaFieldDescriptor {
  field: string;

  /** number, integer, string, datetime  */
  type: DataType;

  title?: string;
  // ....
}

export interface FieldSchema extends TableSchemaFieldDescriptor {
// ...
}

export interface TableSchema {
  fields: TableSchemaFieldDescriptor[];
}


export class Schema implements TableSchema {
// ...
}
```

**Comment by kanitw** [comment]
These proposed sounds reasonable to me.  Please go ahead and make the changes.

**Comment by kanitw** [comment]
https://github.com/vega/compassql/issues/379 is changing the API so we will have to update

- [ ] Update the [`cql-vl2` branch](https://github.com/vega/vega-editor/tree/cql-vl2) in Vega Editor
- [ ] Voyager

and then we're good :)

**Comment by rufuspollock** [comment]
Hi All, this is @rufuspollock. I'm really excited to see this happen - vega and its ecosystem are just **awesome**.

If there is anything I and the other Frictionless Data folks like @pwalsh or @danfowler can do to help just let us know 👍

**Comment by kanitw** [comment]
@rufuspollock 

Thanks -- I think once we have a proper release for our new version of Voyager in React, maybe it's worth adding it to http://frictionlessdata.io/tools/?   Right now, it is still under development so it might be a bit too early to add. :)

**Comment by rufuspollock** [comment]
@kanitw we'd be happy to add now if you want (we can always say - "support upcoming"). This ways we won't forget. You can just do a pull request  on https://github.com/frictionlessdata/frictionlessdata.io/blob/master/tools/index.md
