### ISSUE TITLE
How do I build locally for usage/testing... 

### ISSUE THREAD

**Issue by alphaBenj** [vega/voyager#345]
How do I build locally for usage/testing... Can you point me to the startup script/ method.

**Comment by tafsiri** [comment]
@alphaBenj i believe the project uses npm scripts to build and run. Assuming you have yarn installed you can use `yarn` to install dependencies, `yarn start` to start the dev server `yarn run build` to build. Other npm scripts are listed here -> https://github.com/vega/voyager/blob/vy2/package.json#L19

**Comment by alphaBenj** [comment]
XX-MacBook-Pro:voyager-master ab6$ yarn start
yarn start v0.24.6
$ webpack-dev-server --open --config config/webpack.config.dev.js
sh: webpack-dev-server: command not found
error Command failed with exit code 127.

The link is broken... please help

**Comment by kanitw** [comment]
Have you run yarn to install required dependencies?

**Comment by alphaBenj** [comment]
Instead of asking if I have install dependencies.. it would be helpful to give the commands that would go from zero to fully functional codebase

**Comment by alphaBenj** [comment]
commands to solve are: 
npm install node-sass. 
yarn run build
yarn start

why node-sass is missing - beyond me.   The npm dependencies seem excessive..

**Comment by alphaBenj** [comment]
With local build -- How do I add my own data? Where do the data files go.

**Comment by kanitw** [comment]
> it would be helpful to give the commands that would go from zero to fully functional codebase

We already did in CONTRIBUTING.md, but maybe that's hidden so in https://github.com/vega/voyager/pull/387 we will move them to #387.  

> With local build -- How do I add my own data? Where do the data files go.

The master branch is still under development.  We will add UI for loading custom data soon (https://github.com/vega/voyager/issues/366).
