### ISSUE TITLE
Design how we make program state persistent

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#347]
For example, as a standalone app, we may store things in localStorage -- just in case of refresh, so the app can still maintain local state?

As a wrapped application, how do we provide the API to support saving program state.

**Comment by tafsiri** [comment]
Here are the pieces of the picture I see so far. I'll do it file by file with code stubs

#### libVoyager.tsx
```typescript
public setApplicationState(state: Readonly<StateBase>): void {
  // This new function would allow restoring application state to some
  // value. We also have to decide if we take state with history here or just
  // present state.
  this.render(this.data, this.config, state);
  return;
}


public getApplicationState(): Readonly<StateBase> {
  // Should we pass the whole thing or just 'present'? I'm currently imagining
  // it is just the present state. But i don't know if we want to 'restore' with
  // full history
  return this.store.getState().present;
}

public onStateChange(callback: Function): void {
  // This function would call the callback passed in on every state change,
  // (maybe only the state changes that make it into the history given our
  // pending filtering/grouping pr), passing the new state to the callback
  //
  // Like above should we give it state with history or just present state?
  return;
}
```

#### src/index.tsx
```typescript
// These two values would come from a module that would be responsible for
// defining a persistence strategy (getState and saveState basically).

let initialState = undefined;
let onStateChange = undefined;

// Something along these lines is done. we may provide a custom function if we want to filter
// the state before it goes to the callback. if a custom function is used it would be shared between // this and libVoyager.tsx
store.subscribe(onStateChange);

ReactDOM.render(
    <Provider store={store}>
        <App
            config={config}
            data={data}
            dispatch={store.dispatch}
            state={initialState}
        />
    </Provider>,
    document.getElementById('root')
);
```

#### src/components/app.tsx

```typescript

interface Props extends React.Props<AppBase> {
  config?: VoyagerConfig;
  data?: Data;
  applicationState?: Readonly<StateBase>;
  dispatch: Dispatch<StateWithHistory<Readonly<StateBase>>>;
}


// This would be called by update(), just like setData and setConfig
private setApplicationState(state: Readonly<StateBase>): void {
    // TODO
    // This function would actually do whatever is necessary with redux to set the whole state
    // tree (possibly just triggering an action that handles this.)
    return;
  }
```

Thoughts? Whats missing? At least open question for me was whether we should pass the whole 'state with history' or just 'current state' to persisters. 

ping @kanitw and @vlandham

**Comment by kanitw** [comment]
> At least open question for me was whether we should pass the whole 'state with history' or just 'current state' to persisters.

Looking at most software (e.g., VSCode, Keynote), I don't think we need to preserve the history.  So maybe just "current state" should be sufficient (and more space-efficient)?

**Comment by kanitw** [comment]
I think the API stubs here make sense.  The missing part would be how would we update the whole state, but I guess you're working on that.   (I guess we can do something in the reducer and make sure we clean history after loading a new state?)

A minor note is that `state` below here should be `applicationState` to be consistent with `app.tsx`?

```
        <App
            config={config}
            data={data}
            dispatch={store.dispatch}
            state={initialState}
        />
```

**Comment by tafsiri** [comment]
if the api looks good to you i can proceed. I'm not too worried about updating the whole state (though I haven't picked the exact method yet). While waiting i have temporarily diverted to see if i can make the ui tests run faster (which will make writing tests for this plan easier :).
