### ISSUE TITLE
Undo/Redo leaves UI in inconsistent states from user perspective

### ISSUE THREAD

**Issue by tafsiri** [vega/voyager#349]
Currently undo redo captures all actions, so if a user action has a number of intermediate (internal actions), those will be undone individually. Using [filters](https://github.com/omnidan/redux-undo#filtering-actions) or [groups](https://github.com/omnidan/redux-undo#grouping-actions) 
should help in making undo/redo apply to just user driven actions.

Any thoughts @kanitw?

**Comment by kanitw** [comment]
Good point.  We should definitely use them.  

I guess group might be more reasonable?  (Just guessing -- I'm open to here what you think too)

**Comment by tafsiri** [comment]
Yeah i'd have to look into each a bit more at some point and also how the actions get triggered. At the moment filters seem like they would be simpler to implement/maintain, but haven't looked very deeply at it.

**Comment by kanitw** [comment]
I also haven't looked closely – but I wonder how `filter` deal with redo if some actions are filtered.

**Comment by tafsiri** [comment]
Jotting some notes for self after exploring this for a bit (and before the weekend starts): 

- I think this needs to use groups, and needs a scheme where we can fairly associate a small set of 'follow on' actions with 'starter actions'.

- We can do this by giving each action a grouping level. 1 or 2:
  - Level 1 things start a new groupBy (the name of the action can be used as the group identifier)
  - Level 2 things check the state of the previous history and if the last action is a level 1 or level 2 thing, copy the groupBy identifier from that action so that they are grouped with it.
  - If a thing doesn't have a groupBy it defaults to a level 1 thing. 

- This should work if there isn't a situation where something is both a level 1 and a level 2 thing
