### ISSUE TITLE
Travis may not be running all tests

### ISSUE THREAD

**Issue by tafsiri** [vega/voyager#354]
Currently on master, the lib-voyager tests are failing however travis is not catching this. It might be because two different test suites are being executed, but probably needs some investigation.

Ping @kanitw

**Comment by kanitw** [comment]
@tafsiri  Is it simply because the new ui test hasn't been added to https://github.com/vega/voyager/blob/master/.travis.yml?

**Comment by tafsiri** [comment]
closed by #360
