### ISSUE TITLE
Filter UI 

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#373]
- [x] Read about filter in Vega Lite

  - [x] We won't use Vega expression directly

- [x] Update CompassQL -- to support it  (https://github.com/vega/compassql/issues/366)

- [x] Design State and reducer
  - Although Filter is a part of `transform` *array*  in Vega-Lite (and will be in CompassQL), I don't think we need it to be an array in Voyager (for now). 

-------
- [x] Look at both Tableau and the old UI

- [x] Support Drag and Drop
- [ ] Filter for Quantitative
  - [x] Support entering specific value (Rather than just adjusting range)
  - [ ] Determine the right filter step
- [x] Filter for Nominal + Search Box
  - [x] Clear all
- [x] Filter for Temporal and Time Unit

**Comment by starry97** [comment]
Open #534 for filter step
