### ISSUE TITLE
API for loading visual encoding

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#377]
For example, if the electron app wanna support loading .vl.json file, we need to be able to update the shelf

**Comment by tafsiri** [comment]
Using https://raw.githubusercontent.com/altair-viz/altair-viz.github.io/master/tutorials/getting-started-rst-altair-plot-8.vl.json as an example vl.json file.

```
{
  "spec":{
    "config":{
      "mark":{
        "color":"lightgreen"
      }
    },
    "mark":"bar",
    "encoding":{
      "y":{
        "aggregate":"average",
        "field":"b",
        "axis":{
          "title":"avg(b) by category"
        },
        "type":"quantitative"
      },
      "x":{
        "field":"a",
        "axis":{
          "title":"category"
        },
        "type":"nominal"
      }
    },
    "data":{
      "values":[
        {
          "a":"C",
          "b":2
        },
        {
          "a":"C",
          "b":7
        },
        {
          "a":"C",
          "b":4
        },
        {
          "a":"D",
          "b":1
        },
        {
          "a":"D",
          "b":2
        },
        {
          "a":"D",
          "b":6
        },
        {
          "a":"E",
          "b":8
        },
        {
          "a":"E",
          "b":4
        },
        {
          "a":"E",
          "b":7
        }
      ]
    }
  },
  "mode":"vega-lite",
  "actions":{
    "export":false,
    "source":false,
    "editor":true
  }
}
```

We want to be able to pass in the `spec` key into voyager and have it update its Shelf.spec. I think we should be able to use `export function fromSpecQuery(spec: SpecQuery, oldConfig?: Config): ShelfUnitSpec` from models/spec.ts to do this. We would just pass in an object with `mark`, `transform`, `encodings` and `config`. Skipping `data` as that is stored somewhat differently in the voyager state tree.

**Comment by kanitw** [comment]
This looks good except that the spec is a vega-embed file, which in turn wraps a Vega-LIte file.  (I don't know why Altair is using that as .vl.json.  I'll ask in Vega-dev channel if we should set a different convention for vega-embed file.)

You can find standard .vl.json files here: https://github.com/vega/vega-lite/tree/master/examples/specs

**Comment by tafsiri** [comment]
There is a method in compass that takes a spec and returns a specQuery.

**Comment by kanitw** [comment]
I think the complete steps will be:

1. Given a `spec` read from JSON file, validates with Vega-Lite's JSON schema (maybe with `ajv`) 
2. Given it passes validation, we can safely cast the `spec` to `TopLevelExtendedSpec` (VL). 
3. Check if  `isUnitSpec(spec)` (VL), if not throw warning that we do not support Vega-Lite specifications for layered or multi-view yet. 
4. If the spec is a UnitSpec, then we can call `fromSpec(spec)` (CQL) to get a `SpecQuery`
5. call `fromSpecQuery(specQuery)` to get a `ShelfUnitSpec` object.
