### ISSUE TITLE
Support Basic Connection to Database 

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#380]
maybe SQLite?

**Comment by kanitw** [comment]
I'm putting this in the Voyager Bocoup board for now, but we can prioritize if this is important.  
(Just noting down so that we don't forget about this idea.)

**Comment by kanitw** [comment]
- [ ] load data from SQL
- [ ] data exchange API*

**Comment by psonis** [comment]
any updates on sql integration?

**Comment by kanitw** [comment]
We no longer have plan to do this, but you’re welcome to submit PRs

**Comment by h4gen** [comment]
Hello everybody, I wanted to address this point again. I am wondering why this was moved from the roadmap? Tbh I don't really see the use case of the project, when external databases are not supported. Let's assume I want to use Voyager as a BI tool. Then I want to interact with data that lives in the cloud and is only accessible with a language, I am probably not familiar with. When I want to analyse CSV files I could also use Excel. When I am forced to use a programming language to access my data in the cloud I would probably use pandas. From my perspective Voyager would be nicely located, filling this gap and addressing a real need. Am I missing something?
