### ISSUE TITLE
App state not serializable

### ISSUE THREAD

**Issue by tafsiri** [vega/voyager#398]
In the course of working on https://github.com/vega/voyager-electron/pull/9, it appears that the voyager app state (redux store state) is not serializable. Making an issue here to discuss what would be involved in making it serializable. 

Here are some of the errors i get when trying to load state that has been run through JSON.stringify.  I'll also attach an example state file.

They are unfortunately difficult to trace from the built code that voyager-electron uses.

<img width="677" alt="screen shot 2017-06-20 at 3 18 02 pm" src="https://user-images.githubusercontent.com/26408/27351558-c847b6f2-55cb-11e7-8c95-f357fce1077b.png">

<img width="664" alt="screen shot 2017-06-20 at 3 18 18 pm" src="https://user-images.githubusercontent.com/26408/27351562-cc8c9692-55cb-11e7-902e-1e3fa1db7cbf.png">

Link to gist with sample serialized state: https://gist.github.com/tafsiri/c6a6ef84379ed39c7777df8a06a68fb1

So what do folks already know about schema.cardinality and other parts of the state tree with respect to serialization?

Ping @vlandham @kanitw

**Comment by vlandham** [comment]
for voyager-server, I am currently serializing the `Schema` in the following way:

* The server calls `buildSchema` via https://github.com/vega/voyager/blob/master/src/api/api.ts#L76
* The server extracts the `fieldSchema[]` array and sends that to the client here: https://github.com/vega/voyager-server/blob/master/server/utils.ts#L14
* The client re-hydrates a new `Schema` object by passing in the fieldSchemas: https://github.com/vega/voyager/blob/master/src/api/api.ts#L70

While `Schema` is not serializable, the `fieldSchema[]` inside of it is. `fieldSchema[]` is data table schema format, with some additional fields. 

You can see its definition in compassql: https://github.com/vega/compassql/blob/master/src/schema.ts#L39

Is it possible to add a serialize / deserialize process to the saving of the state? if so, perhaps we could use a similar process as voyager-server

**Comment by tafsiri** [comment]
Thanks Jim, i'll look at this more closely. Whatever gets done i would look to do in the getApplicationState and setApplicationState of voyager itself (that way voyager-electron only gets something that voyager can actually directly restore).

**Comment by tafsiri** [comment]
This will also depend on #377. I now think it isn't practical or reliable to serialize the whole state tree (too many of its types are defined outside the project with no guarantee of serializability). Now I'm thinking of only serializing the minimal amount of data that voyager can then use to get back to a particular state (and will result in a smaller file). This will basically boil down to things we can pass through props. 

Let's take data and config (our current props), if we pass these in, voyager can reconstruct a schema. Then as specified in #377, if we can pass in a shelf, voyager will reconstruct the result. That way we will not have to serialize the schema or the result object.

If this route proves successful, then the setApplicationState action will actually just use existing reducers and we can remove the newer setApplicationState reducer.

**Comment by tafsiri** [comment]
As i think of it more, another advantage to not serializing derived state is that it makes the serialized state a little less brittle with respect to changes in the code base and how those things are stored or computed. Sticking to the public API will make it easier to version. 

Also do we need to think about versioning if we expect people to write these to files?

**Comment by vlandham** [comment]
i like this approach. add another api call for shelf creation - and it seems like we are pretty much there.

**Comment by kanitw** [comment]
> Let's take data and config (our current props), if we pass these in, voyager can reconstruct a schema. Then as specified in #377, if we can pass in a shelf, voyager will reconstruct the result. That way we will not have to serialize the schema or the result object.

The problem is that schema will contain user-specified information in the future (very soon -- e.g., from https://github.com/vega/voyager/issues/368).  Thus, we can't reconstruct schema purely from the data.  

> This will also depend on #377. I now think it isn't practical or reliable to serialize the whole state tree (too many of its types are defined outside the project with no guarantee of serializability)

If schema and results are the only two things that are not currently serializable, we can also restructure them if needed since they are in CompassQL and CompassQL is primarily designed as a backend for Voyager.  

Also we will contain more state for each result item, allowing users to directly modify small aspects of the results (e.g., toggling log scales).  Thus queries may be completely reproduced from the shelf as well.  

That said, if we really need to go down this route, we may need to think how to restructure the state to decouple the state that are reproducible or not. However, I believe that we can refactor the CompassQL structure to be more serializable.

**Comment by kanitw** [comment]
> Also do we need to think about versioning if we expect people to write these to files?

Yep. Let's discuss that later today.  

> Sticking to the public API will make it easier to version.

I'm not sure what defines the public API here.  

In any case, one possible idea is we can make the Voyager version increments based on whether the changes in `State` include breaking changes.

**Comment by tafsiri** [comment]
Okay @kanitw. Lets discuss a bit later today. I'll try and outline parts of the state that I think aren't serializable. We may want to separate serializable data from derived data (and things have behaviour and functions attached as well).

**Comment by kanitw** [comment]
> things have behaviour and functions attached as well

Yes, I think we should not use class for things in state, but instead wrap a pure object with helper function or a wrapper class.

**Comment by tafsiri** [comment]
yep and that is a thing which we would want to happen in compassql/vega.

**Comment by kanitw** [comment]
CompassQL is easy.  Here is  one issue I just created for CompassQL https://github.com/vega/compassql/issues/386

Is there any method in Vega that needs that?

**Comment by tafsiri** [comment]
working on ways of inspecting what might cause problems. I'll update in a bit.

**Comment by tafsiri** [comment]
but i say that mostly because i don't know the vega-lite types in depth, e.g.

```
import {EncodingQuery} from 'compassql/build/src/query/encoding';
import {AggregateOp} from 'vega-lite/build/src/aggregate';
import {Channel} from 'vega-lite/build/src/channel';
import {Encoding} from 'vega-lite/build/src/encoding';
import {Mark as VLMark} from 'vega-lite/build/src/mark';
import {TimeUnit} from 'vega-lite/build/src/timeunit';
import {Type} from 'vega-lite/build/src/type';
```

They may all be serializable (since vega-lite) is declarative, but i don't know if these (or other things) wrap them with functionality.

**Comment by kanitw** [comment]
All of these are just interface / enums so none of them would be a problem.  
(You can use "go to definition" command to check each of them if you want, but no need to all of them are serializable otherwise Vega-Lite couldn't be a JSON format.) 

(Btw, these are in Vega-Lite, not Vega.)

**Comment by tafsiri** [comment]
Excellent. If i can assume that every type imported from vega-lite is serializable then that does make things a bit easier (fewer things to look at).

**Comment by tafsiri** [comment]
Currently depends on https://github.com/vega/compassql/issues/386 as well
