### ISSUE TITLE
Bug when loading default dataset attributes to shelf

### ISSUE THREAD

**Issue by tafsiri** [vega/voyager#401]
Is anybody else getting this error on master when adding a field from the default dataset to the shelf? @kanitw @vlandham?

![screen shot 2017-06-22 at 5 27 34 pm](https://user-images.githubusercontent.com/26408/27456772-4199b67c-5770-11e7-8bc5-6dac5aa2a56d.png)

This only seems to happen with the defaut dataset. It might be related to the compassql bump

**Comment by tafsiri** [comment]
To reproduce try adding the q1 or q2 fields to the shelf.

**Comment by kanitw** [comment]
It seems specific to the mock dataset -- definitely worth investigating more but probably not that blocking.

**Comment by kanitw** [comment]
This might be removed once we do #442?

**Comment by kanitw** [comment]
Closing as we're doing #442
