### ISSUE TITLE
Test if the store listener approach is working fine for loading state / loading spec

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#466]

**Comment by vlandham** [comment]
* saving / loading state for basic example looks to work in `voyager-electron`

**Comment by vlandham** [comment]
According to https://github.com/vega/voyager-electron/pull/15 these changes also work for loading spec. 

So i think we should be good, once the two PRs are merged!

**Comment by kanitw** [comment]
Yay, I'll close this issue then ;)
