### ISSUE TITLE
Field added to the encoding preview cannot be removed

### ISSUE THREAD

**Issue by starry97** [vega/voyager#505]
When hovering over the wildcard field in specified views, the field added to the encoding preview cannot be removed. At the same time, it triggers all plots to rerender.
![bug](https://user-images.githubusercontent.com/19985016/28798005-09e9b6c2-75f8-11e7-8de6-40db8febf3ff.gif)

**Comment by kanitw** [comment]
I think we should decouple `specPreview` from `shelf`.
Maybe `stateBase.shelf.specPreview` => `stateBase.shelfPreview.spec`? 

(This query is automatically re-generated based on whether `shelf` has changed.)
