### ISSUE TITLE
Problems with deploy script

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#569]
Looking at vega.github.io/voyager

- [x] The app does not fill the screen somehow.  
- [ ] Image is not included 
- [ ] Generated index.html in gh-pages does not have the right path to `static`  (It should be just `static/`, not `/static` 

If you guys could help with this, that would be great. 

I guess we should be able to re-publish using:
`npm run clean && npm run build && node scripts/deploy.js`

**Comment by kanitw** [comment]
This is part of `webpack.prod.config.js` and `scripts/build.js`.

Btw, I figured the css problem.

**Comment by felixcodes** [comment]
Resolved path issue with PR #654. Opened issue #660 for not-included image problem.
