### ISSUE TITLE
Cannot read 'aggregate' of null

### ISSUE THREAD

**Issue by jhoffswell** [vega/voyager#576]
The following combination produces an error for the population dataset. Error: "Uncaught (in promise) TypeError: Cannot read property 'aggregate' of null"

<img width="434" alt="brokenspec-populationaggregate" src="https://user-images.githubusercontent.com/3392218/29188152-0df3ab7a-7dc7-11e7-97e5-0c1d716202a5.png">

**Comment by kanitw** [comment]
This should be a part of https://github.com/vega/voyager/issues/607
