### ISSUE TITLE
Cannot read property 'spec' of undefined

### ISSUE THREAD

**Issue by jhoffswell** [vega/voyager#580]
For the population dataset, placing any of the fields on the 'text' shelf produces an error and no specification as seen below. The error is: "Uncaught (in promise) TypeError: Cannot read property 'spec' of undefined"

<img width="954" alt="error-populationspecundefined" src="https://user-images.githubusercontent.com/3392218/29188492-0f820012-7dc8-11e7-8fbd-eea26a82c9bd.png">

**Comment by kanitw** [comment]
Actually same problem for car.

**Comment by kanitw** [comment]
Part of https://github.com/vega/voyager/issues/607
