### ISSUE TITLE
Certain temporal bins fail for certain spec types with wildcard fields

### ISSUE THREAD

**Issue by mcorrell** [vega/voyager#582]
In the Crimea dataset, the following things work:
![image](https://user-images.githubusercontent.com/8633790/29188466-fdc21c86-7dc7-11e7-83a0-05b8d39fef03.png)
Wildcard field, bar type, temporal bin of "month"
![image](https://user-images.githubusercontent.com/8633790/29188486-0e481010-7dc8-11e7-94e2-3447b0653e69.png)
Explicit choice of field, bar type, temporal bin of "year"
However:
![image](https://user-images.githubusercontent.com/8633790/29188517-24d84b6a-7dc8-11e7-8736-637f80cbb940.png)
Wildcard field, bar type, temporal bin of "year" does NOT generate a plot.

Other situations where the wildcard field and the temporal value on x doesn't result in plots include (but are not limited to):
unbinned time with any mark type other than auto, point, rule, circle, square.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/compassql/pull/402
