### ISSUE TITLE
This query produces no plots

### ISSUE THREAD

**Issue by yyyliu** [vega/voyager#586]
I am using the default "Jobs" dataset. As is shown in the screenshot, with the setup of these fields, Voyager does not return any visualization. There was no related error in the console.

<img width="1386" alt="screen shot 2017-08-10 at 12 56 32 pm" src="https://user-images.githubusercontent.com/25254084/29189665-42751bcc-7dcc-11e7-9fa8-485d5e192b21.png">

By the way, if I dragged "year" to the "y" encoding, the console logs an error saying this (but nonetheless generates appropriate visualizations):

```
Uncaught (in promise) Error: Unrecognized scale range value: "category20"
    at t.a (error.js:2)
    at C (scale.js:234)
    at o (scale.js:47)
    at spec.js:33
    at Array.forEach (<anonymous>)
    at t.a (spec.js:32)
    at n (view.js:56)
    at Object.t.a (parse.js:8)
    at t.renderVega (index.tsx:30)
    at t.componentDidMount (index.tsx:40)
```

**Comment by kanitw** [comment]
This should be a part of https://github.com/vega/voyager/issues/606
