### ISSUE TITLE
Better sorting UI

### ISSUE THREAD

**Issue by felixcodes** [vega/voyager#625]
Create a popup-component for sorting data. Tableau's implementation:

![image](https://user-images.githubusercontent.com/17525561/29433549-7371a9e2-8354-11e7-8530-38a417df7025.png)

**Comment by kanitw** [comment]
I think we can have a similar UI as a Pop-up component 

For "sort by", we can have by alphabetic or by field for now.

**Comment by kanitw** [comment]
Duplicate of https://github.com/vega/voyager/issues/761
