### ISSUE TITLE
Module not found: Error: Can't resolve 'voyager' when trying to embed

### ISSUE THREAD

**Issue by rotaricristian** [vega/voyager#630]
I am trying to embed voyager in an angular 2 project and during `npm install` i get these  warnings : 

![image](https://user-images.githubusercontent.com/26246251/29457175-2e1fb1c0-8419-11e7-98c3-bdd9d319926a.png)
 which seems to be a dependency of datavoyager. During `ng serve` I get the following error 
```
Error in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'voyager' in '...\src\app'
Parsed request is a module using description file: ...\package.json
...
```
I also tried installing datavoyager manually as a node module but these errors occur 
![image](https://user-images.githubusercontent.com/26246251/29457445-7a5a3cee-841a-11e7-9971-efc309e83679.png)

I mention that i have added voyager as a dependency in the package.json file 
```
...
 "voyager": "git://github.com/vega/voyager.git",
...
```
and I used the following code for instantiation
```javascript
const libVoyager = require('voyager');

const container = document.getElementById("voyager-embed");
const config = undefined;
const data = undefined;
const voyagerInstance = libVoyager.CreateVoyager(container, config, data)
```

Any ideas?

**Comment by kanitw** [comment]
For react-hot-loader, we definitely should fix a version. 
For adding Voyager as a dependency, we don't included compiled files on github, please use our released versions on NPM. Note that Voyager 2 is still under development, so if you find any problems, please feel free to report bugs. 

Btw, it would be great to hear what you're using Voyager 2 for. :)

**Comment by kanitw** [comment]
I have update README.me to suggest installing the package via NPM release (not via github).  

@felixcodes  -- can you fix the version like discussed and we can close this issue.  :)

**Comment by rotaricristian** [comment]
@kanitw  we use it in a data preparation and transformation tool.
You can have a look at it here: https://github.com/datagraft/data-fixer
