### ISSUE TITLE
Restructure the application model to support multiple screens / tabs

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#647]
- [ ] all the actions now need one more parameter: tab/screen id

- [x] modify store to have one more level of nesting for things that are different in different tabs
  - [x] list what should be different

- [x] modify reducer to have one more level of nesting

**Comment by ZeningQu** [comment]
For my own app, I want to add a panel that contains all the charts and all the dashboards the user has created on the right side of the screen (e.g., like below)

![screen shot 2018-01-11 at 10 05 42 pm](https://user-images.githubusercontent.com/822034/34861777-9e005a56-f71b-11e7-832f-51140205f3c5.png)

Do you think something like this would be ok for Voyager? @kanitw

**Comment by kanitw** [comment]
For "chart", it's unclear from just one screenshot how the chart +new button would work. 

For dashboard, unless you add dashboard to Voyager, having a tab for dashboard doesn't make sense.

**Comment by ZeningQu** [comment]
I will add dashboard as I need this in my own app anyways.

The chart thing is a bit tricky. I think it makes more sense if you are creating one view at a time, and you have a collection of single views. For Voyager, since you already have multiple views and you already have bookmarks, having a chart collection doesn't make much sense.

Maybe I have add the Chart component but have it disabled by default in Voyager...?

**Comment by ZeningQu** [comment]
Right now this is the `UndoableStateBase`:

```ts
customWildcardFields: CustomWildcardField[];
shelf: Shelf;
result: ResultIndex;
dataset: Dataset;
```

This represents one tab in Voyager. To support multiple tabs we can store an array of these tab states in the store state. Let say we declare an interface

```ts
interface chartState = {		// chartState or tabState?
	customWildcardFields: CustomWildcardField[];
	shelf: Shelf;
	result: ResultIndex;
	dataset: Dataset;
	chartID: string; 		// I want chartID and chartTitle for my app
	chartTitle: string;
}
```

So the store state would be like:

```ts
{
        persistent: ...;
	undoable: {
		future: [];
		past: [];
		present: { // I will call this the new UndoableStateBase
			charts: chartState[];
			dashboards: dashboardState[];
		}
	}
}

interface dashboardState = {  // I also need an array of dashboards in my app
	dashboardID: string;
	dashboardTitle: string;
	containsChartID: []
}
```

**Comment by kanitw** [comment]
- That said, you might want to think about what's the right name.  Maybe `SingleViewTab` is one candidate.  (In Voyager, even if the recommendation is enabled, the interface is still for authoring a single view plot.) 

I'd say call it a tab and it will be less confusing.   (If you turn recommendation off, a tab shows one chart but it's still a reasonable terminology.) 

- if you have list of charts already, do you really need `chartID`?  Basically you can use index of the item in the array.  

- I think your first PR shouldn't involve dashboard ... that's another conversation.  At very least, the information you have here is insufficient for real usage anyway.  That said, for Dashboard UI if you design the components in a way that's generalizable, it would be worth adding to core Voyager too.  But you will have to think about how to make it work for Voyager if there is no bigger list of items like you do on the left. 

One possibility for Voyager is: 
```
tabs: (SIngleViewTabState | MultiViewTabState)[]
```

For now, please do

```
tabs: SIngleViewTabState[]
```

note that  this makes sense for your app, but not Voyager -- so you're not suppose to pollute Voyager. 
```
{ // I will call this the new UndoableStateBase
			charts: chartState[];
			dashboards: dashboardState[];
		}
```

You might just wanna define the state of your app to be slightly different :)

**Comment by ZeningQu** [comment]
Thanks! I will do 
```
tabs: SingleViewTabState[]
``` 
for now.
