### ISSUE TITLE
npm install voyager error: Invalid tag name "#"

### ISSUE THREAD

**Issue by rotaricristian** [vega/voyager#661]
The following error occurs when installing datavoyager via npm: 

![image](https://user-images.githubusercontent.com/26246251/29667370-6e363258-88dc-11e7-8305-493571d6a262.png)

The error came along with the _2.0.0-alpha.11_ release while previous releases work fine.

**Comment by kanitw** [comment]
Thanks for reporting -- We will use a different mechanism to add comment to package.json.
