### ISSUE TITLE
build folder inside build folder

### ISSUE THREAD

**Issue by ZeningQu** [vega/voyager#668]
Voyager has a build folder inside the build folder

![image](https://user-images.githubusercontent.com/822034/29800633-f8b89fe2-8c1f-11e7-94a3-e2ade245c07a.png)

**Comment by felixcodes** [comment]
I got this one! Unassigned everyone.

**Comment by felixcodes** [comment]
So it looks like the `ts-loader` module `webpack.config.lib.js` was producing that second build folder. outDir property in `tsconfig.json` was set to ./build/ but should really be set to the current directly. I'll push the fix :)
