### ISSUE TITLE
Embedding question

### ISSUE THREAD

**Issue by davidanthoff** [vega/voyager#745]
I'm trying to embed voyager in a simple HTML file but am quite lost where to start. Probably because I'm just not familiar enough with things, so any pointers would be most appreciated.

My (naive?) idea was:
1. I create an empty folder called ``vtest`` on my disc
2. I run ``npm install datavoyager`` in ``vtest``
3. I add a file ``index.html`` to ``vtest`` with the following content:
````html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <title>Voyager 2</title>
  <link href="./node_modules/datavoyager/build/style.css" rel="stylesheet">

  <style>
    html {
      height: 100%;
    }

    body {
      margin: 0;
      padding: 0;
      height: 100%;
    }

    #root {
      height: 100%;
      padding: 0;
    }

  </style>
</head>

<body>
  <div id="root"></div>

  <!-- Dependencies -->
  <script src="./node_modules/react/dist/react.js"></script>
  <script src="./node_modules/react-dom/dist/react-dom.js"></script>

  <!-- Main -->
  <script src="./node_modules/datavoyager/build/lib-voyager.js"></script>

    <script>
        const libVoyager = require('voyager');

        const container = document.getElementById("root");
        const config = undefined;
        const data = undefined;
        const voyagerInstance = libVoyager.CreateVoyager(container, config, data)
    </script>

</body>

</html>
````
4. I open that file in my browser and might see the voyager app?

I don't, and I'm probably doing things wrong at every corner :) Any help would be appreciated.

**Comment by felixcodes** [comment]
Hi @davidanthoff! I believe the intention of the `Embed Voyager` section in our README is to show how to embed Voyager into another _NodeJS_ web application. My apologies if it was misleading.

I believe you're currently trying to embed Voyager in a simple client-side app without a node server. The Voyager app does not display when you open `index.html` file in your browser because the `require` portion of `const libVoyager = require('voyager');` is a Node.js module that does not work in the client-side without additional libraries and some funky syntax.

Please let me know if you need any help embedding Voyager into a Node app!

**Comment by davidanthoff** [comment]
Yes, I'm trying to embed it in a standalone HTML file without a node server. The broader goal is to integrate this with the julia data ecoystem. Here is a high level outline of what I hope to do. I've created a dplyr like query framework in julia that allows one to pipe data through various manipulation verbs. I'd like to add a new verb ``voyager`` that one can pipe data into, and then the voyager UI should pop up. For example, something like this julia code:
````julia
load("data.csv") |> @filter(_.age>20) |> voyager()
````
My idea is that if one does this on the REPL, the call to ``voyager()`` would just write out an HTML file to disc and open that file in a web browser. If one does this inside VS Code (I also maintain the VS Code julia extension), it would open a tab with the voyager UI. For both cases I can't really start a node server and it would be really fantastic if I could get things to work in just a standalone HTML file.

In terms of workflow, I imagine that folks would then use the voyager UI to explore the data, and once they have a graph they like, they would export it in the vega-lite format. They could then use that vega-lite spec in julia in one of the two following forms:
````julia
load("data.csv") |> @filter(_.age>20) |> load("thesavedspec.vl.json")
# OR
load("data.csv") |> @filter(_.age>20) |> vl"""
VEGA LITE SPEC GOES HERE INLINE
"""
````
So essentially one could use the interactive UI to fiddle with the figure until it looks good, and then use the vega-lite spec to create a script that can reliably reproduce that figure.

On that note, I'd also be interested to integrate Lyra, but not clear to me whether that is still maintained?

**Comment by davidanthoff** [comment]
On the technical note, I guess your suggestion about require.js are the right strategy. Right now I'm stuck though, most likely because my client side javascript/HTML skills are, uhhh, poor :)

What I'm trying now is this as ``index.html``:
````html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <title>Voyager 2</title>
  <link href="./node_modules/datavoyager/build/style.css" rel="stylesheet">

  <style>
    html {
      height: 100%;
    }

    body {
      margin: 0;
      padding: 0;
      height: 100%;
    }

    #root {
      height: 100%;
      padding: 0;
    }

  </style>
  <script data-main="app.js" src="require.js"></script>
</head>

<body>
  <div id="root"></div>
</body>

</html>
````
I've added the ``require.js`` file to the folder. My ``app.js`` now looks like this:
````js
requirejs.config({
    'baseUrl': 'node_modules',
    // module name mapped to CDN url
    paths: {
        'react': 'react/dist/react',
        'react-dom': 'react-dom/dist/react-dom',
        'lib-voyager': 'datavoyager/build/lib-voyager'
    }
});

requirejs(['react', 'react-dom', 'lib-voyager'], function(react,reactdom,libvoyager) {
    var container = document.getElementById("root");
    var config = undefined;
    var data = undefined;
    var voyagerInstance = libVoyager.CreateVoyager(container, config, data)
});
````
At that point I get a whole bunch of errors that complain that it can't find files like ``react-css-modules.js`` etc. I assume that one of ``react``, ``react-dom`` and ``lib-voyager`` is requiring that, and I probably just have to configure all those paths as well? But there are 26 of those errors, so I'm wondering whether there is something less manual...

Any help with this is really greatly appreciated. I am entirely aware that this is more about my lack of javascript skill then about voyager...

**Comment by davidanthoff** [comment]
Alright, I have something running using browserify. I’ll report back how things are going once I have the Julia stuff working.

**Comment by davidanthoff** [comment]
Alright, I've got a working julia package in pretty good shape: https://github.com/davidanthoff/DataVoyager.jl.

Essentially you pipe data into voyager on the julia REPL, it will open an electron window that hosts voyager and then you can explore the data.

I'll have a lot more specific question as I polish this integration, but I'll open separate issues for that.
