### ISSUE TITLE
Translation to spanish (or other languages)

### ISSUE THREAD

**Issue by mazito** [vega/voyager#766]
From what I understand, Voyager uses only English for its current UI. 
Is there some intention or interest to support a multi language version of Voyager ?
I may be able to contribute with a translation to Spanish.
Is that possible ? 
Thanks in advance.
Mario

**Comment by kanitw** [comment]
We don't have the resource to work on multiple languages of the tools.  

You're welcome to propose a design for the infrastructure for translating all text in the applications and implement it.  (But let's talk about the design first.)

**Comment by mazito** [comment]
Thanks for your answer. 
My intention was just text translation if something already existed in place.  
I will look at the code and come back with some proposal. 
Need to find the time for it first :-)

**Comment by kanitw** [comment]
Okie.  We'll close it for now since we don't plan to do it.  Feel free to re-open once you wanna post a proposal.
