### ISSUE TITLE
Grid view for raw data

### ISSUE THREAD

**Issue by davidanthoff** [vega/voyager#772]
It would be quite nice if there was a very simple grid/table view for the raw data available somehow in the UI. I know the focus of this is about visualization, but sometimes it can be super handy to just take a quick peek at the underlying raw data, and it would be nice if one could do that in the same UI and wouldn't have to use another tool for that.

**Comment by kanitw** [comment]
This is something we thought about too. However, given that we are working on integrating Voyager as a plugin for JupyterLab, users can easily use Jupyter to peek at the underlying raw data.  

Thus, given we have limited resources, I don't think we will work on this.
