### ISSUE TITLE
Tooltip is not working properly 😱

### ISSUE THREAD

**Issue by ZeningQu** [vega/voyager#779]
In some plots tooltip shows up, in other plots it doesn't!

See gif below (on `master`, the default view):

![tooltip 1](https://user-images.githubusercontent.com/822034/36709688-fe58a8b4-1b2d-11e8-9462-73ffb122da66.gif)

In the first plot, tooltip is working ok, although it tend to disappear on the bottom bar.

In the second plot, tooltip doesn't show up.

![tooltip 2](https://user-images.githubusercontent.com/822034/36710208-52617262-1b31-11e8-84d5-b262bf0b7c6a.gif)

In the third plot, tooltip seems ok. Also tend to disappear on the bottom bar.

On the fourth plot, tooltip doesn't show up, but that's probably expected because it's a line chart?

On the fifth plot, tooltip only seems to show up between the gaps of the bars.

**Comment by kanitw** [comment]
Feel free to help submit a fix.  :)

**Comment by ZeningQu** [comment]
I switched to `svg` renderer today and tooltip is working again. With `canvas` renderer tooltip still doesn't work. So I suspect it's a recent canvas issue...

**Comment by ZeningQu** [comment]
Found tooltip to be working with both `canvas` and `svg`. So I'm closing this issue for now.
