### ISSUE TITLE
Custom Encoding: Mark Channels

### ISSUE THREAD

**Issue by ssharif6** [vega/voyager#783]
This deals with custom encoding for the mark channels -- size, color, shape, detail, text.

* Be able to set default values for the different mark channels (i.e changing default color from #4682b4 to another color)

**Comment by kanitw** [comment]
Since #757 is pretty much incomplete and contains a lot of details that's better not split as a different issue, Im gonna close this.  

> Be able to set default values for the different mark channels (i.e changing default color from #4682b4 to another color)

That is customizing fixed color `value`, which is a different issue -- https://github.com/vega/voyager/issues/662.
