### ISSUE TITLE
Error in using non-summative aggregate function

### ISSUE THREAD

**Issue by zzhangjii** [vega/voyager#795]
In jupyterlab_voyager, with the newest v2.0.0-alpha.18 version, 
when using those non-summative aggregate functions (mean, max, min...), I will receive this warn message:
**Can not stack when the aggregate function is non-summative**

the vl.json detail:
`{"data":{"url":"https://vega.github.io/vega-datasets/data/population.json","format":{"type":"json"}},"mark":"bar","encoding":{"color":{"field":"sex","type":"nominal","scale":{"range":["lightblue","pink"]}},"x":{"field":"age","type":"nominal","scale":{"rangeStep":12}},"y":{"aggregate":"mean","field":"people","type":"quantitative"}}}`
and the graph and warning msg:
<img width="927" alt="screen shot 2018-04-15 at 6 31 35 pm" src="https://user-images.githubusercontent.com/11495372/38786405-9afa92d0-40dc-11e8-8a2c-6762457df002.png">

**Comment by kanitw** [comment]
Note that the plot has "mean" aggregate so stacking "mean" value is also not a good idea.

**Comment by kanitw** [comment]
This issue is actually due to Voyager using an older version of Vega-Lite.  Newer version of Vega-Lite allows this without warning. 

cc: @felixcodes
