### ISSUE TITLE
Expanding detail channel shows empty popup

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#804]
- Better add a customizer for text's `format`
- Better not show caret for detail and make it unclickable

**Comment by ssharif6** [comment]
Is the Text Channel's `format` property supported in Compass? I remember making a customizer for the text channel and format property, but there was no effect.

**Comment by ssharif6** [comment]
Split this issue 
> Better add a customizer for text's format

To #807 

This issue will just concern not displaying caret for `detail` channel and make it unclickable
