### ISSUE TITLE
Feature Request: Cartesian Product of Categoricals

### ISSUE THREAD

**Issue by dvisztempacct** [vega/voyager#833]
In the visualizations I've written for a data set I've been working with recently, I have a few categorical features with low cardinality, and it has made a lot of sense to me to combine these features into a single feature.

In Voyager (and I assume also in CompassQL) this doesn't appear to be possible, yet, but at least in my situation it would have really made Voyager a much more powerful tool.

**Comment by kanitw** [comment]
Data wrangling like this is beyond the scope of this tool.  We envision the main use case of Voyager to be with environment like Jupyter, where you can easily do this in python or other languages.
