### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by danielballan** [vega/voyager#857]
Hello! I am interested in this project as one front-end for a [structured data access server](https://github.com/bluesky/tiled) that we are building at Brookhaven National Lab. The deployment at https://vega.github.io/voyager/ works great, but I notice that the cadence of voyager [releases](https://github.com/vega/voyager/releases) has slowed, and the last release was in July 2018. Is this project actively developed and maintained? If not, is there a successor project I should be looking at instead?

**Comment by domoritz** [comment]
We started voyager as a research project and maintaining a UI project long term without a company or specific use case is difficult. Right now, we are not actively maintaining this project as a production tool but we will occasionally push some updates as we still use it for prototyping research ideas. For example, yesterday I updated this project to use GitHub actions and we are working on updating the dependencies.

We are very open to people contributing and reviving the project. However, don't expect anyone from the Vega team to develop features or fix bugs if you create an issue on GitHub.

At the core of Voyager are https://vega.github.io/vega-lite/ and CompassQL, the former of which is actively maintained and well supported. You could probably build your own version of Voyager without too much effort (i.e. a month of work or so) if you only need a specific feature set.

**Comment by danielballan** [comment]
Thanks!
