### ISSUE TITLE
Voyager is not working with Angular 

### ISSUE THREAD

**Issue by iqbalh178692** [vega/voyager#875]
import {AfterViewInit, Component} from '@angular/core';
import {CreateVoyager} from "datavoyager";

@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {

constructor() {
}
ngAfterViewInit() {
const container = document.getElementById('voyager-embed');
const config = undefined;
const data: any = {
'values': [
{ 'fieldA': 'A', 'fieldB': 28 },
{ 'fieldA': 'B', 'fieldB': 55 }
]
};
CreateVoyager(container, config, data);
}
}
`

I getting such output:
./node_modules/vega_lib/index.js:19:0-21:24 - Error: Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)

ERROR in node_modules/vega-lite/build/src/util.d.ts(78,16): error TS2344: Type 'keyof T' does not satisfy the constraint 'string'. Type 'string | number | symbol' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'. node_modules/compassql/build/src/schema.d.ts(22,12): error TS2304: Cannot find name 'DLFieldProfile'. node_modules/compassql/build/src/schema.d.ts(24,28): error TS2304: Cannot find name 'DLFieldProfile'. node_modules/compassql/build/src/schema.d.ts(27,29): error TS2304: Cannot find name 'DLFieldProfile'. node_modules/compassql/build/src/schema.d.ts(93,32): error TS2304: Cannot find name 'DLFieldProfile'.

**Comment by domoritz** [comment]
We don't have the cycles to help with bundler issues. I don't think this is a bug with our code but how your angular setup processes ts.
